spring:
  application:
    name: spring-cloud-gateway
  cloud:
    gateway:
      routes:
        - id: config_route
          ## 是否能进入到路由，拦截判断
          predicates:
            - Path=/gateway/**
          filters:
            - StripPrefix=1
            - Custom=Lee
          ## 被拦截到之后要映射到哪儿去
          uri: http://localhost:8088/
        - id: cookie_route
          predicates:
            ##如果cookie里面携带了key = name , value=mic
            - Cookie=name,mic
          uri: https://www.baidu.com
        - id: auth_route
          predicates:
            - Path=/auth/**
            - Auth=jessionid
          filters:
            - StripPrefix=1
          uri: https://www.bing.com
        - id: lb_route
          predicates:
            - Path=/lb/**
          filters:
            - StripPrefix=1
          uri: lb://user-service/

        - id: ratelimiter_route
          predicates:
            - Path=/ratelimiter/**
          filters:
            - StripPrefix=1
            - name: RequestRateLimiter
              args:
                deny-empty-key: true
                keyResolver: '#{@iPAddressKeyResolver}'
                ## 令牌生成速率
                redis-rate-limiter.replenishRate: 1
                ## 令牌桶容量
                redis-rate-limiter.burstCapacity: 2
          uri: lb://user-service/
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
  redis:
    port: 6379
    host: xxxx
server:
  port: 9090

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
