spring:
  application:
    name: spring-cloud-gateway
  cloud:
    gateway:
      routes:
        ## 是否能进入到路由，拦截判断
        - predicates:
            - Path=/gateway/**
          filters:
            - StripPrefix=1
          ## 被拦截到之后要映射到哪儿去
          uri: http://localhost:8088/
server:
  port: 9090